# Generated by Django 4.0.10 on 2024-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('editeur', models.CharField(max_length=42)),
                ('description', models.TextField(null=True)),
                ('dateparution', models.DateTimeField(auto_now_add=True, verbose_name='Date de Parution')),
            ],
        ),
    ]
