# Generated by Django 4.0.10 on 2024-09-02 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('nbpages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='dispo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='genre',
            field=models.CharField(choices=[('MAN', 'Management'), ('IT', 'High Tech'), ('CUI', 'Cuisine')], default='IT', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='year_created',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='dateparution',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de parution'),
        ),
    ]
