# Generated by Django 4.0.10 on 2024-09-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaux', '0003_article_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
